module corbak{

typedef Object IOR;

struct Date {
    short year;
    short month;
    short day;
	short hour;
	short minute;
	short seconde;
};

//Block exceptions
exception droitsInsufisants { string raison; short id; };
exception certificatInvalide { string raison; short id; };
exception authentificationEchouee { string raison; short id; };

struct Signature {
	string hash;
};
struct Certificat {
	Date dateExpiration;
	IOR ACemmetrice;
	string pubClef;
	Signature sign;
};

struct Message {       
	Signature sign;		   
	string text;		   
	boolean estChiffre;    
};

interface AV { 
	boolean revocCertif( in Certificat certif);
	boolean verification (in Certificat certificat) raises (certificatInvalide);
};

interface AC {	
	boolean revocCertif(in Certificat certif) raises (certificatInvalide);
	Certificat generationCertificat(in string PubKey, in Date dateExpiration, in string ACemmetrice , in Signature sign); 
	boolean verification(in Signature sign);
};

interface AE{
	boolean authentification(in string login, in string password) raises (authentificationEchouee);
	boolean revocCertif(in string login, in string password, in Certificat certif) raises (droitsInsufisants ,certificatInvalide);
	Certificat genererCertificat(in string PubKey);
};

interface Client{		
	void envoyerMessage (in Message msg, in Certificat certif);
	void envoyer (in Certificat certif);
};

};
